export const Types = {

  //HOME SCREEN ACTIONS - 
  LOAD_HOME_SCREEN: 'LOAD_HOME_SCREEN',
  LOAD_HOME_SCREEN_BANNER: 'LOAD_HOME_SCREEN_BANNER',
  LOAD_HOME_SCREEN_CATE_LAPTOP: 'LOAD_HOME_SCREEN_CATE_LAPTOP',
  LOAD_HOME_SCREEN_CATE_SMARTPHONE: 'LOAD_HOME_SCREEN_CATE_SMARTPHONE',
  LOAD_HOME_SCREEN_CATE_SKINCARE: 'LOAD_HOME_SCREEN_CATE_SKINCARE',
  LOAD_HOME_SCREEN_CATE_WOMEN_DRESS: 'LOAD_HOME_SCREEN_CATE_WOMEN_DRESS',
  LOAD_HOME_SCREEN_CATE_MEN_DRESS: 'LOAD_HOME_SCREEN_CATE_MEN_DRESS',
  LOAD_HOME_SCREEN_CATE_HOME_DECOR: 'LOAD_HOME_SCREEN_CATE_HOME_DECOR',
  LOAD_HOME_SCREEN_CATE_FURNITURE: 'LOAD_HOME_SCREEN_CATE_FURNITURE',

  //USER ACTIONS -
  USER_REGISTER: 'USER_REGISTER',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_TOGGLE_LOGIN: 'USER_TOGGLE_LOGIN',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',

  //PRODUCT ACTIONS - 
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
  UPDATE_PRODUCT_QUANTITY: 'UPDATE_PRODUCT_QUANTITY',
  FETCH_PRODUCT_DETAILS: 'FETCH_PRODUCT_DETAILS',

  //CART ACTIONS - 
  VIEW_CART: 'VIEW_CART',
  FETCH_CART: 'FETCH_CART',

  //ORDER ACTIONS - 
  CREATE_ORDER: 'CREATE_ORDER',
  VIEW_ORDER: 'VIEW_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',

  //SEARCH ACTIONS -
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',

  //PAYMENT & CHECKOUT ACTIONS - 
  INITIATE_PAYMENT: 'INITIATE_PAYMENT',
  COMPLETE_PAYMENT: 'COMPLETE_PAYMENT',
  SET_SHIPPING_ADD: 'SET_SHIPPING_ADD',

  //INTERACTIONS ACTION - 
  SHARE_PRODUCT: 'SHARE_PRODUCT',

  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
};
